language: node_js
node_js:
  - '10'

# before_script:
#   - psql -c 'create database travis_db;' -U postgres

script:
  - npm run test

after_success: 
  - npm install -g codeclimate-test-reporter
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
  